# Generated by Django 4.0 on 2024-09-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_video_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='features',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
